[package]
name = "broker"
version = "0.1.0"
edition = "2021"
[workerspace]
members = [
    "config"
]

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
config = { path = "../config" }
